name: Automated Fancode JSON Updater

on:
  schedule:
    - cron: '*/7 * * * *' 
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download JSON and Update Log
        run: |
          curl -sS -o fancode.json "https://raw.githubusercontent.com/drmlive/fancode-live-events/refs/heads/main/fancode.json"
          export TZ="Asia/Kolkata"
          echo "ðŸš€ Fancode Synced Successfully | IST: $(date +'%Y-%m-%d %H:%M:%S') | ID: $RANDOM" >> fancode.txt

      - name: Configure Git User
        run: |
          git config --global user.email "kajju3864@gmail.com"
          git config --global user.name "kajju027"

      - name: Commit and Push
        run: |
          export TZ="Asia/Kolkata"
          git add fancode.json fancode.txt
          git commit -m "Fancode Database Updated âœ… [$(date +'%d-%m-%Y %H:%M')] #$RANDOM" --allow-empty
          git push
          
